language: python
python:
- '3.2'
jdk:
- oraclejdk7
before_install:
- sudo apt-get update -qq
- if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm
  ia32-libs ia32-libs-multiarch; fi
- wget -O android-sdk-linux.tgz http://dl.google.com/android/android-sdk_r22.2.1-linux.tgz
- tar -zxf android-sdk-linux.tgz
- export ANDROID_HOME=`pwd`/android-sdk-linux
- export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${ANDROID_HOME}/build-tools/17.0.0/:${ANDROID_HOME}/tools/proguard/bin/
- echo y | android update sdk --filter android-17,platform-tools,build-tools-17.0.0
  --all --no-ui --force
- wget --no-check-certificate https://dl.dropboxusercontent.com/u/4976322/ingress/lib.tar.gz
- tar xvfz lib.tar.gz
- wget --no-check-certificate https://dl.dropboxusercontent.com/u/4976322/ingress/apk/ingress-latest.apk
install:
- pip install -r requirements.txt --use-mirrors
before_script:
- gem install travis-artifacts
script:
- rm *.diff; wget -o /dev/null $patchurl && patch -p1 -i *.diff
- git config --global user.email "a@b.c"
- git config --global user.name "Ingress apk mod"
- python bin/import_apk.py ingress-latest.apk > /dev/null
- python bin/release.py > /dev/null
after_success:
- rm ingress-latest.apk
- curl -T release/ingress-latest/ingress-latest-broot-*-mute.apk ftp://$ftpserver/ --user $ftpuser:$ftppw && rm release/*mute*.apk
- curl -T release/ingress-latest/ingress-latest-broot-*.apk ftp://$ftpserver/ --user $ftpuser:$ftppw && rm release/*.apk
env:
  global:
  - secure: s/scNVIiWPncK4LMQITzWLQpEkNw1ZcGC9b2XgqycI6WIAorqQ330/gVZ9WuFDqTLP0bsjrnkHv48OnZ9e4UtAkAZFnrTie+R1dyA3w9AsJuPQXPL70rmfLEjjdEOs8E13+EgfDtb7/0tGiJE0iFvnlEYTKm9h2D20c2UeOZTL0=
  - secure: gVi0eJ88PQLd3mnU72YmBJEJY/mutaSCBU+jC17OPpAoasT1J4X93rL+kuyQ0exd4+gXCfL2nnFh2D/sP3BohjF6GiGzKK/ubM/0N60I+ODyTt1hp7LQiu9HeupSQEvHp+3eRv9cuWNuAsqewyVE8xtYKLzxQm+rlAeA4fWXgVY=
  - secure: CuntLjQp2/5rg758OHD8/cB495aknBfLkGXUW1FsXKeGYVII339IKn8slIbqHSA3XBRJMeKtpqvjqZ5KnSQqdkpnJ/qWTrOH6OX78KUwoJVuYgLGM9HiID8mBl6c/kPkViZf3lm2X3pmeEOsPeKsLto6c7y3uMPpNI/Mo0AUUwc=
  - secure: aFZpmbzwF9ha/MSs4E1HbIyqoUVDYC2GKT7lt0MxepMTtZV9mZS+UsJ/RVTrzLHlAHeZxw/L97oQpuSI4FvQ+tqaezMWPSuImu2GXVjFNwRHkQVCao3VikqU4SPyEKbBNuSMAtGaKEy3VPBAo/ELnWAMErO4dD5nrXwspGTq63M=
